name: dingdong
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  beeba:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: sh .devcontainer/start-container.sh
      - run: php artisan serve --host=0.0.0.0 --port=8000 &
      - run: npx playwright install
      - run: npx playwright install-deps
      - run: curl --fail-with-body http://localhost:8000
      - run: npx playwright test

