name: dingdong
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  beeba:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Yarn
        run: npm install
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: npx playwright test

